<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BasicRelationService" targetNamespace="http://tempuri.org/">
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <xs:element name="CorsOptionsRequest">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="CorsOptionsRequestResponse">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationsList">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="type" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="whereClause" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationsListResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetRelationsListResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationsList_StandardAttributesWhere">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="type" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="whereClause" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="whereClauseStandardAttributes" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationsList_StandardAttributesWhereResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetRelationsList_StandardAttributesWhereResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationsListPaged">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="type" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="whereClause" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="whereClauseStandardAttributes" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="pageIndex" type="xs:int"/>
            <xs:element minOccurs="0" name="pageSize" type="xs:int"/>
            <xs:element minOccurs="0" name="sortColumn" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="sortDescending" type="xs:boolean"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationsListPagedResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetRelationsListPagedResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationTypesList">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationTypesListResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetRelationTypesListResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetNewRelationIndexFields">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetNewRelationIndexFieldsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetNewRelationIndexFieldsResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationGeneralFields">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationGeneralFieldsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetRelationGeneralFieldsResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationDefaultAuthorizationProfile">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetRelationDefaultAuthorizationProfileResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetRelationDefaultAuthorizationProfileResult" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetNewRelationAuthorizationProfiles">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetNewRelationAuthorizationProfilesResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetNewRelationAuthorizationProfilesResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetExistingRelationAuthorizationProfiles">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relId" type="xs:int"/>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetExistingRelationAuthorizationProfilesResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetExistingRelationAuthorizationProfilesResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetExistingRelationIndexFields">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relId" type="xs:int"/>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetExistingRelationIndexFieldsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetExistingRelationIndexFieldsResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CreateRelation">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="authorizationProfileID" type="xs:int"/>
            <xs:element minOccurs="0" name="processID" type="xs:int"/>
            <xs:element minOccurs="0" name="indexFields" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CreateRelationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="CreateRelationResult" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DeleteRelation">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relId" type="xs:int"/>
            <xs:element minOccurs="0" name="relType" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DeleteRelationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="DeleteRelationResult" type="xs:boolean"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="UpdateRelation">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="relId" type="xs:int"/>
            <xs:element minOccurs="0" name="relationType" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="authorizationProfileID" type="xs:int"/>
            <xs:element minOccurs="0" name="processID" type="xs:int"/>
            <xs:element minOccurs="0" name="indexFields" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="UpdateRelationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="UpdateRelationResult" type="xs:boolean"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="PrepareDate">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="date" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="format" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="PrepareDateResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="PrepareDateResult" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IBasicRelationServiceContract_CorsOptionsRequest_InputMessage">
    <wsdl:part name="parameters" element="tns:CorsOptionsRequest"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_CorsOptionsRequest_OutputMessage">
    <wsdl:part name="parameters" element="tns:CorsOptionsRequestResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationsList_InputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationsList"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationsList_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationsListResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationsList_StandardAttributesWhere_InputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationsList_StandardAttributesWhere"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationsList_StandardAttributesWhere_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationsList_StandardAttributesWhereResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationsListPaged_InputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationsListPaged"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationsListPaged_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationsListPagedResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationTypesList_InputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationTypesList"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationTypesList_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationTypesListResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetNewRelationIndexFields_InputMessage">
    <wsdl:part name="parameters" element="tns:GetNewRelationIndexFields"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetNewRelationIndexFields_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetNewRelationIndexFieldsResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationGeneralFields_InputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationGeneralFields"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationGeneralFields_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationGeneralFieldsResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationDefaultAuthorizationProfile_InputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationDefaultAuthorizationProfile"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetRelationDefaultAuthorizationProfile_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetRelationDefaultAuthorizationProfileResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetNewRelationAuthorizationProfiles_InputMessage">
    <wsdl:part name="parameters" element="tns:GetNewRelationAuthorizationProfiles"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetNewRelationAuthorizationProfiles_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetNewRelationAuthorizationProfilesResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetExistingRelationAuthorizationProfiles_InputMessage">
    <wsdl:part name="parameters" element="tns:GetExistingRelationAuthorizationProfiles"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetExistingRelationAuthorizationProfiles_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetExistingRelationAuthorizationProfilesResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetExistingRelationIndexFields_InputMessage">
    <wsdl:part name="parameters" element="tns:GetExistingRelationIndexFields"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_GetExistingRelationIndexFields_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetExistingRelationIndexFieldsResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_CreateRelation_InputMessage">
    <wsdl:part name="parameters" element="tns:CreateRelation"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_CreateRelation_OutputMessage">
    <wsdl:part name="parameters" element="tns:CreateRelationResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_DeleteRelation_InputMessage">
    <wsdl:part name="parameters" element="tns:DeleteRelation"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_DeleteRelation_OutputMessage">
    <wsdl:part name="parameters" element="tns:DeleteRelationResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_UpdateRelation_InputMessage">
    <wsdl:part name="parameters" element="tns:UpdateRelation"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_UpdateRelation_OutputMessage">
    <wsdl:part name="parameters" element="tns:UpdateRelationResponse"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_PrepareDate_InputMessage">
    <wsdl:part name="parameters" element="tns:PrepareDate"/>
  </wsdl:message>
  <wsdl:message name="IBasicRelationServiceContract_PrepareDate_OutputMessage">
    <wsdl:part name="parameters" element="tns:PrepareDateResponse"/>
  </wsdl:message>
  <wsdl:portType name="IBasicRelationServiceContract">
    <wsdl:operation name="CorsOptionsRequest">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicBaseServiceContract/CorsOptionsRequest" message="tns:IBasicRelationServiceContract_CorsOptionsRequest_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicBaseServiceContract/CorsOptionsRequestResponse" message="tns:IBasicRelationServiceContract_CorsOptionsRequest_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetRelationsList">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationsList" message="tns:IBasicRelationServiceContract_GetRelationsList_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationsListResponse" message="tns:IBasicRelationServiceContract_GetRelationsList_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetRelationsList_StandardAttributesWhere">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationsList_StandardAttributesWhere" message="tns:IBasicRelationServiceContract_GetRelationsList_StandardAttributesWhere_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationsList_StandardAttributesWhereResponse" message="tns:IBasicRelationServiceContract_GetRelationsList_StandardAttributesWhere_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetRelationsListPaged">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationsListPaged" message="tns:IBasicRelationServiceContract_GetRelationsListPaged_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationsListPagedResponse" message="tns:IBasicRelationServiceContract_GetRelationsListPaged_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetRelationTypesList">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationTypesList" message="tns:IBasicRelationServiceContract_GetRelationTypesList_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationTypesListResponse" message="tns:IBasicRelationServiceContract_GetRelationTypesList_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetNewRelationIndexFields">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetNewRelationIndexFields" message="tns:IBasicRelationServiceContract_GetNewRelationIndexFields_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetNewRelationIndexFieldsResponse" message="tns:IBasicRelationServiceContract_GetNewRelationIndexFields_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetRelationGeneralFields">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationGeneralFields" message="tns:IBasicRelationServiceContract_GetRelationGeneralFields_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationGeneralFieldsResponse" message="tns:IBasicRelationServiceContract_GetRelationGeneralFields_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetRelationDefaultAuthorizationProfile">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationDefaultAuthorizationProfile" message="tns:IBasicRelationServiceContract_GetRelationDefaultAuthorizationProfile_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetRelationDefaultAuthorizationProfileResponse" message="tns:IBasicRelationServiceContract_GetRelationDefaultAuthorizationProfile_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetNewRelationAuthorizationProfiles">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetNewRelationAuthorizationProfiles" message="tns:IBasicRelationServiceContract_GetNewRelationAuthorizationProfiles_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetNewRelationAuthorizationProfilesResponse" message="tns:IBasicRelationServiceContract_GetNewRelationAuthorizationProfiles_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetExistingRelationAuthorizationProfiles">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetExistingRelationAuthorizationProfiles" message="tns:IBasicRelationServiceContract_GetExistingRelationAuthorizationProfiles_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetExistingRelationAuthorizationProfilesResponse" message="tns:IBasicRelationServiceContract_GetExistingRelationAuthorizationProfiles_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="GetExistingRelationIndexFields">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetExistingRelationIndexFields" message="tns:IBasicRelationServiceContract_GetExistingRelationIndexFields_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/GetExistingRelationIndexFieldsResponse" message="tns:IBasicRelationServiceContract_GetExistingRelationIndexFields_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="CreateRelation">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/CreateRelation" message="tns:IBasicRelationServiceContract_CreateRelation_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/CreateRelationResponse" message="tns:IBasicRelationServiceContract_CreateRelation_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="DeleteRelation">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/DeleteRelation" message="tns:IBasicRelationServiceContract_DeleteRelation_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/DeleteRelationResponse" message="tns:IBasicRelationServiceContract_DeleteRelation_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="UpdateRelation">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/UpdateRelation" message="tns:IBasicRelationServiceContract_UpdateRelation_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/UpdateRelationResponse" message="tns:IBasicRelationServiceContract_UpdateRelation_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="PrepareDate">
      <wsdl:input wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/PrepareDate" message="tns:IBasicRelationServiceContract_PrepareDate_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBasicRelationServiceContract/PrepareDateResponse" message="tns:IBasicRelationServiceContract_PrepareDate_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IBasicRelationServiceContract" type="tns:IBasicRelationServiceContract">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CorsOptionsRequest">
      <soap:operation soapAction="http://tempuri.org/IBasicBaseServiceContract/CorsOptionsRequest" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRelationsList">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetRelationsList" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRelationsList_StandardAttributesWhere">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetRelationsList_StandardAttributesWhere" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRelationsListPaged">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetRelationsListPaged" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRelationTypesList">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetRelationTypesList" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetNewRelationIndexFields">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetNewRelationIndexFields" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRelationGeneralFields">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetRelationGeneralFields" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRelationDefaultAuthorizationProfile">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetRelationDefaultAuthorizationProfile" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetNewRelationAuthorizationProfiles">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetNewRelationAuthorizationProfiles" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetExistingRelationAuthorizationProfiles">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetExistingRelationAuthorizationProfiles" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetExistingRelationIndexFields">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/GetExistingRelationIndexFields" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateRelation">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/CreateRelation" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DeleteRelation">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/DeleteRelation" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateRelation">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/UpdateRelation" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PrepareDate">
      <soap:operation soapAction="http://tempuri.org/IBasicRelationServiceContract/PrepareDate" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BasicRelationService">
    <wsdl:port name="BasicHttpBinding_IBasicRelationServiceContract" binding="tns:BasicHttpBinding_IBasicRelationServiceContract">
      <soap:address location="http://swdms01-acc/Doc(Base)WCF/BasicRelationService.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>