version: '{build}-({branch})'

max_jobs: 1

image: Visual Studio 2017
skip_tags: true
clone_folder: C:\projects\CVnHR-Open-Source

environment:
  fast_finish: true

services:
- mssql2017
- postgresql
- iis

before_build:
  appveyor-retry nuget restore

build:
  project: QNH.Overheid.CVnHR.sln
  parallel: true
  verbosity: minimal

test_script: off

notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

cache:
  - packages -> QNH.Overheid.CVnHR.sln
