-- ORACLE VIEW
CREATE OR REPLACE VIEW QNH_VW_VESTIGINGSBIACTIVITEIT (
	 Id,
    ISHOOFDSBIACTIVITEIT,
    SbiCode_id,
    VESTIGING_ID
) AS
SELECT 
	REPLACE(REPLACE(v.SC_IDENTIF, 'nhr.comVestg.', ''), 'nhr.nietComVestg.', '') + va.FK_SBI_ACTIVITEIT_CODE  AS Id,
	va.INDICATIE_HOOFDACTIVITEIT AS ISHOOFDSBIACTIVITEIT,
  va.FK_SBI_ACTIVITEIT_CODE AS SbiCode_id,
  CAST(REPLACE(REPLACE(v.SC_IDENTIF, 'nhr.comVestg.', ''), 'nhr.nietComVestg.', '') AS NUMBER(10,0)) AS VESTIGING_ID
FROM VESTG_ACTIVITEIT va
  INNER JOIN VESTG v
  on v.SC_IDENTIF = va.FK_VESTG_NUMMER;