-- ORACLE VIEW
CREATE OR REPLACE VIEW QNH_VW_FUNCTIEVERVULLING (
	ID,	--NUMBER(10,0)
	FUNCTIE, --	NVARCHAR2(255 CHAR)
	FUNCTIETITEL, --	NVARCHAR2(255 CHAR)
	VOLLEDIGENAAM,	--NVARCHAR2(255 CHAR)
	SCHORSING,	--NVARCHAR2(255 CHAR)
	LANGSTZITTENDE,	--NVARCHAR2(255 CHAR)
	BEVOEGDHEID,	--NVARCHAR2(255 CHAR)
	HANDELINGSBEKWAAM,	--NVARCHAR2(255 CHAR)
	KVKINSCHRIJVING_ID	--NUMBER(10,0)
) AS
SELECT 
 ROWNUM                    as ID,
  f.FUNCTIE                as FUNCTIE,
  f.FUNCTIONARISTYPERING   as FUNCTIETITEL,
  'geen naam in BRMO'      as VOLLEDIGENAAM,
  'geen schorsing in BRMO' as SCHORSING,
  f.SOORT_BEV              as LANGSZITTENDE,
  f.VOLLEDIG_BEPERKT_VOLMACHT as BEVOEGDHEID,
  f.BV_SOORT_HANDELING     as HANDELINGSBEKWAAM,
  CAST(REPLACE(p.SC_IDENTIF, 'nhr.maatschAct.kvk.', '') AS NUMBER(10,0)) as KVKINSCHRIJVING_ID
FROM FUNCTIONARIS f 
  INNER JOIN PRS p 
  on f.FK_SC_LH_PES_SC_IDENTIF = p.SC_IDENTIF;