-- ORACLE VIEW
CREATE OR REPLACE VIEW QNH_VW_KVKINSCHRIJVING (
	ID,
  NAAM,
  KVKNUMMER,
  PEILMOMENT,
  INGEVOEGDOP,
  GELDIGTOT,
  OPGEVRAAGDOP,
  REGISTRATIEDATUMAANVANG,
  REGISTRATIEDATUMEINDE,
  DATUMOPRICHTING,
  DATUMUITSCHRIJVING,
  PERSOONRECHTSVORM,
  UITGEBREIDERECHTSVORM,
  BIJZONDERERECHTSTOESTAND,
  REDENINSOLVENTIE,
  BEPERKINGINRECHTSHANDELING,
  EIGENAARHEEFTGEDEPONEERD,
  VOLLEDIGENAAMEIGENAAR,
  FULLTIMEWERKZAMEPERSONEN,
  PARTTIMEWERKZAMEPERSONEN,
  TOTAALWERKZAMEPERSONEN,
  GEPLAATSTKAPITAAL,
  GESTORTKAPITAAL,
  RECHTERLIJKEUITSPRAAK,
  HANDELSNAMEN
) AS
SELECT
  O.KVK_NUMMER													AS ID,
  S2.NAAM														AS NAAM,
  CAST(O.KVK_NUMMER as VARCHAR2(16))													AS KVKNUMMER,
  TO_DATE(O.DATUM_AANVANG, 'YYYYMMDD')							AS PEILMOMENT,
  TO_DATE(O.DATUM_AANVANG, 'YYYYMMDD')							AS INGEVOEGDOP,
  TO_DATE(NVL(MA.DATUM_EINDE_GELDIG,'99991231'), 'YYYYMMDD')    AS GELDIGTOT,
  TO_DATE(O.DATUM_AANVANG, 'YYYYMMDD')							AS OPGEVRAAGDOP,
  TO_DATE(MA.DATUM_AANVANG, 'YYYYMMDD')							AS REGISTRATIEDATUMAANVANG,
  TO_DATE(MA.DATUM_EINDE_GELDIG, 'YYYYMMDD')					AS REGISTRATIEDATUMEINDE,
  TO_DATE(O.DATUM_AANVANG, 'YYYYMMDD')							AS DATUMOPRICHTING,
  TO_DATE(O.DATUM_EINDE, 'YYYYMMDD')							AS DATUMUITSCHRIJVING,
  S.CLAZZ														AS PERSOONRECHTSVORM,
  S.CLAZZ														AS UITGEBREIDERECHTSVORM,
  NULL															AS BIJZONDERERECHTSTOESTAND,
  NULL															AS REDENINSOLVENTIE,
  NULL															AS BEPERKINGINRECHTSHANDELING,
  NULL															AS EIGENAARHEEFTGEDEPONEERD,
  S.NAAM														AS VOLLEDIGENAAMEIGENAAR,
  CAST(0 as NUMBER(10,0))										AS FULLTIMEWERKZAMEPERSONEN,
  CAST(0 as NUMBER(10,0))										AS PARTTIMEWERKZAMEPERSONEN,
  CAST(0 as NUMBER(10,0))										AS TOTAALWERKZAMEPERSONEN,
  NULL															AS GEPLAATSTKAPITAAL,
  NULL															AS GESTORTKAPITAAL,
  NULL															AS RECHTERLIJKEUITSPRAAK,
  'TODO'														AS HANDELSNAMEN
FROM 
  ONDRNMNG O
  LEFT OUTER JOIN MAATSCHAPP_ACTIVITEIT MA
    ON O.KVK_NUMMER = MA.KVK_NUMMER
  LEFT OUTER JOIN SUBJECT S
    ON MA.FK_4PES_SC_IDENTIF = S.IDENTIF
  LEFT OUTER JOIN SUBJECT S2
    ON S2.IDENTIF LIKE '%' || MA.FK_3OND_KVK_NUMMER;