//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QNH.Overheid.KernRegister.Business.Integration
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/", ConfigurationName = "Security.SecuritySoap")]
    public interface SecuritySoap
    {

        // CODEGEN: Generating message contract since element name userName from namespace http://acanthis.com/DocNet/WS_API/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://acanthis.com/DocNet/WS_API/Login", ReplyAction = "*")]
        QNH.Overheid.KernRegister.Business.Integration.LoginResponse Login(QNH.Overheid.KernRegister.Business.Integration.LoginRequest request);

        // CODEGEN: Generating message contract since element name userName from namespace http://acanthis.com/DocNet/WS_API/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://acanthis.com/DocNet/WS_API/Troy", ReplyAction = "*")]
        QNH.Overheid.KernRegister.Business.Integration.TroyResponse Troy(QNH.Overheid.KernRegister.Business.Integration.TroyRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://acanthis.com/DocNet/WS_API/Logout", ReplyAction = "*")]
        bool Logout();

        // CODEGEN: Generating message contract since element name userName from namespace http://acanthis.com/DocNet/WS_API/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://acanthis.com/DocNet/WS_API/LoginRadius", ReplyAction = "*")]
        QNH.Overheid.KernRegister.Business.Integration.LoginRadiusResponse LoginRadius(QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LoginRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Login", Namespace = "http://acanthis.com/DocNet/WS_API/", Order = 0)]
        public QNH.Overheid.KernRegister.Business.Integration.LoginRequestBody Body;

        public LoginRequest()
        {
        }

        public LoginRequest(QNH.Overheid.KernRegister.Business.Integration.LoginRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/")]
    public partial class LoginRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string userName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string password;

        public LoginRequestBody()
        {
        }

        public LoginRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LoginResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "LoginResponse", Namespace = "http://acanthis.com/DocNet/WS_API/", Order = 0)]
        public QNH.Overheid.KernRegister.Business.Integration.LoginResponseBody Body;

        public LoginResponse()
        {
        }

        public LoginResponse(QNH.Overheid.KernRegister.Business.Integration.LoginResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/")]
    public partial class LoginResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool LoginResult;

        public LoginResponseBody()
        {
        }

        public LoginResponseBody(bool LoginResult)
        {
            this.LoginResult = LoginResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class TroyRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Troy", Namespace = "http://acanthis.com/DocNet/WS_API/", Order = 0)]
        public QNH.Overheid.KernRegister.Business.Integration.TroyRequestBody Body;

        public TroyRequest()
        {
        }

        public TroyRequest(QNH.Overheid.KernRegister.Business.Integration.TroyRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/")]
    public partial class TroyRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string userName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string password;

        public TroyRequestBody()
        {
        }

        public TroyRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class TroyResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "TroyResponse", Namespace = "http://acanthis.com/DocNet/WS_API/", Order = 0)]
        public QNH.Overheid.KernRegister.Business.Integration.TroyResponseBody Body;

        public TroyResponse()
        {
        }

        public TroyResponse(QNH.Overheid.KernRegister.Business.Integration.TroyResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/")]
    public partial class TroyResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool TroyResult;

        public TroyResponseBody()
        {
        }

        public TroyResponseBody(bool TroyResult)
        {
            this.TroyResult = TroyResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LoginRadiusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "LoginRadius", Namespace = "http://acanthis.com/DocNet/WS_API/", Order = 0)]
        public QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequestBody Body;

        public LoginRadiusRequest()
        {
        }

        public LoginRadiusRequest(QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/")]
    public partial class LoginRadiusRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string userName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string password;

        public LoginRadiusRequestBody()
        {
        }

        public LoginRadiusRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LoginRadiusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "LoginRadiusResponse", Namespace = "http://acanthis.com/DocNet/WS_API/", Order = 0)]
        public QNH.Overheid.KernRegister.Business.Integration.LoginRadiusResponseBody Body;

        public LoginRadiusResponse()
        {
        }

        public LoginRadiusResponse(QNH.Overheid.KernRegister.Business.Integration.LoginRadiusResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://acanthis.com/DocNet/WS_API/")]
    public partial class LoginRadiusResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool LoginRadiusResult;

        public LoginRadiusResponseBody()
        {
        }

        public LoginRadiusResponseBody(bool LoginRadiusResult)
        {
            this.LoginRadiusResult = LoginRadiusResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecuritySoapChannel : QNH.Overheid.KernRegister.Business.Integration.SecuritySoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuritySoapClient : System.ServiceModel.ClientBase<QNH.Overheid.KernRegister.Business.Integration.SecuritySoap>, QNH.Overheid.KernRegister.Business.Integration.SecuritySoap
    {

        public SecuritySoapClient()
        {
        }

        public SecuritySoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public SecuritySoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SecuritySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SecuritySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNH.Overheid.KernRegister.Business.Integration.LoginResponse QNH.Overheid.KernRegister.Business.Integration.SecuritySoap.Login(QNH.Overheid.KernRegister.Business.Integration.LoginRequest request)
        {
            return base.Channel.Login(request);
        }

        public bool Login(string userName, string password)
        {
            QNH.Overheid.KernRegister.Business.Integration.LoginRequest inValue = new QNH.Overheid.KernRegister.Business.Integration.LoginRequest();
            inValue.Body = new QNH.Overheid.KernRegister.Business.Integration.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            QNH.Overheid.KernRegister.Business.Integration.LoginResponse retVal = ((QNH.Overheid.KernRegister.Business.Integration.SecuritySoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNH.Overheid.KernRegister.Business.Integration.TroyResponse QNH.Overheid.KernRegister.Business.Integration.SecuritySoap.Troy(QNH.Overheid.KernRegister.Business.Integration.TroyRequest request)
        {
            return base.Channel.Troy(request);
        }

        public bool Troy(string userName, string password)
        {
            QNH.Overheid.KernRegister.Business.Integration.TroyRequest inValue = new QNH.Overheid.KernRegister.Business.Integration.TroyRequest();
            inValue.Body = new QNH.Overheid.KernRegister.Business.Integration.TroyRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            QNH.Overheid.KernRegister.Business.Integration.TroyResponse retVal = ((QNH.Overheid.KernRegister.Business.Integration.SecuritySoap)(this)).Troy(inValue);
            return retVal.Body.TroyResult;
        }

        public bool Logout()
        {
            return base.Channel.Logout();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNH.Overheid.KernRegister.Business.Integration.LoginRadiusResponse QNH.Overheid.KernRegister.Business.Integration.SecuritySoap.LoginRadius(QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequest request)
        {
            return base.Channel.LoginRadius(request);
        }

        public bool LoginRadius(string userName, string password)
        {
            QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequest inValue = new QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequest();
            inValue.Body = new QNH.Overheid.KernRegister.Business.Integration.LoginRadiusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            QNH.Overheid.KernRegister.Business.Integration.LoginRadiusResponse retVal = ((QNH.Overheid.KernRegister.Business.Integration.SecuritySoap)(this)).LoginRadius(inValue);
            return retVal.Body.LoginRadiusResult;
        }
    }
}
