//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace QNH.Overheid.KernRegister.Business.SignaalService {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/insolventiewijziging/2016/01")]
    [System.Xml.Serialization.XmlRootAttribute("Insolventiewijziging", Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/insolventiewijziging/2016/01", IsNullable=false)]
    public partial class InsolventiewijzigingType : SignaalType {
        
        private string startdatumField;
        
        private MaatschappelijkeActiviteitType heeftBetrekkingOpField;
        
        /// <remarks/>
        public string startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
            }
        }
        
        /// <remarks/>
        public MaatschappelijkeActiviteitType heeftBetrekkingOp {
            get {
                return this.heeftBetrekkingOpField;
            }
            set {
                this.heeftBetrekkingOpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class MaatschappelijkeActiviteitType {
        
        private string kvkNummerField;
        
        private EnumeratieType nonMailingField;
        
        private string totaalWerkzamePersonenField;
        
        private EigenaarType heeftAlsEigenaarField;
        
        private VestigingType[] wordtUitgeoefendInField;
        
        /// <remarks/>
        public string kvkNummer {
            get {
                return this.kvkNummerField;
            }
            set {
                this.kvkNummerField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType nonMailing {
            get {
                return this.nonMailingField;
            }
            set {
                this.nonMailingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string totaalWerkzamePersonen {
            get {
                return this.totaalWerkzamePersonenField;
            }
            set {
                this.totaalWerkzamePersonenField = value;
            }
        }
        
        /// <remarks/>
        public EigenaarType heeftAlsEigenaar {
            get {
                return this.heeftAlsEigenaarField;
            }
            set {
                this.heeftAlsEigenaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wordtUitgeoefendIn")]
        public VestigingType[] wordtUitgeoefendIn {
            get {
                return this.wordtUitgeoefendInField;
            }
            set {
                this.wordtUitgeoefendInField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class EnumeratieType {
        
        private string codeField;
        
        private string omschrijvingField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/voortzettingenoverdracht/2016/01")]
    public partial class VoortzettingEnOverdrachtType {
        
        private string[] betrokkenVestigingenField;
        
        private EnumeratieType rolBijVoortzettingOverdrachtField;
        
        private string kvkNummerField;
        
        private string persoonRechtsvormField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vestigingsnummer", IsNullable=false)]
        public string[] betrokkenVestigingen {
            get {
                return this.betrokkenVestigingenField;
            }
            set {
                this.betrokkenVestigingenField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType rolBijVoortzettingOverdracht {
            get {
                return this.rolBijVoortzettingOverdrachtField;
            }
            set {
                this.rolBijVoortzettingOverdrachtField = value;
            }
        }
        
        /// <remarks/>
        public string kvkNummer {
            get {
                return this.kvkNummerField;
            }
            set {
                this.kvkNummerField = value;
            }
        }
        
        /// <remarks/>
        public string persoonRechtsvorm {
            get {
                return this.persoonRechtsvormField;
            }
            set {
                this.persoonRechtsvormField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/nieuweinschrijving/2016/01")]
    public partial class Aanleiding {
        
        private string omschrijvingField;
        
        private string kvkNummerField;
        
        /// <remarks/>
        public string omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        public string kvkNummer {
            get {
                return this.kvkNummerField;
            }
            set {
                this.kvkNummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class VestigingType {
        
        private string vestigingsnummerField;
        
        private LocatieType bezoekAdresField;
        
        private ActiviteitType[] activiteitField;
        
        private EnumeratieType isHoofdvestigingField;
        
        /// <remarks/>
        public string vestigingsnummer {
            get {
                return this.vestigingsnummerField;
            }
            set {
                this.vestigingsnummerField = value;
            }
        }
        
        /// <remarks/>
        public LocatieType bezoekAdres {
            get {
                return this.bezoekAdresField;
            }
            set {
                this.bezoekAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activiteit")]
        public ActiviteitType[] activiteit {
            get {
                return this.activiteitField;
            }
            set {
                this.activiteitField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType isHoofdvestiging {
            get {
                return this.isHoofdvestigingField;
            }
            set {
                this.isHoofdvestigingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class LocatieType {
        
        private PostcodeType postcodeField;
        
        /// <remarks/>
        public PostcodeType postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class PostcodeType {
        
        private string cijfercombinatieField;
        
        private string lettercombinatieField;
        
        /// <remarks/>
        public string cijfercombinatie {
            get {
                return this.cijfercombinatieField;
            }
            set {
                this.cijfercombinatieField = value;
            }
        }
        
        /// <remarks/>
        public string lettercombinatie {
            get {
                return this.lettercombinatieField;
            }
            set {
                this.lettercombinatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class ActiviteitType {
        
        private string sbiCodeField;
        
        private EnumeratieType isHoofdactiviteitField;
        
        /// <remarks/>
        public string sbiCode {
            get {
                return this.sbiCodeField;
            }
            set {
                this.sbiCodeField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType isHoofdactiviteit {
            get {
                return this.isHoofdactiviteitField;
            }
            set {
                this.isHoofdactiviteitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NatuurlijkPersoonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NietNatuurlijkPersoonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RechtsPersoonType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class PersoonType {
        
        private string persoonRechtsvormOudField;
        
        private string persoonRechtsvormField;
        
        /// <remarks/>
        public string persoonRechtsvormOud {
            get {
                return this.persoonRechtsvormOudField;
            }
            set {
                this.persoonRechtsvormOudField = value;
            }
        }
        
        /// <remarks/>
        public string persoonRechtsvorm {
            get {
                return this.persoonRechtsvormField;
            }
            set {
                this.persoonRechtsvormField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class NatuurlijkPersoonType : PersoonType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RechtsPersoonType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class NietNatuurlijkPersoonType : PersoonType {
        
        private string rsinField;
        
        /// <remarks/>
        public string rsin {
            get {
                return this.rsinField;
            }
            set {
                this.rsinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class RechtsPersoonType : NietNatuurlijkPersoonType {
        
        private LocatieType bezoekAdresField;
        
        private ActiviteitType[] activiteitField;
        
        /// <remarks/>
        public LocatieType bezoekAdres {
            get {
                return this.bezoekAdresField;
            }
            set {
                this.bezoekAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activiteit")]
        public ActiviteitType[] activiteit {
            get {
                return this.activiteitField;
            }
            set {
                this.activiteitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class EigenaarType {
        
        private NatuurlijkPersoonType natuurlijkPersoonField;
        
        private RechtsPersoonType rechtsPersoonField;
        
        /// <remarks/>
        public NatuurlijkPersoonType natuurlijkPersoon {
            get {
                return this.natuurlijkPersoonField;
            }
            set {
                this.natuurlijkPersoonField = value;
            }
        }
        
        /// <remarks/>
        public RechtsPersoonType rechtsPersoon {
            get {
                return this.rechtsPersoonField;
            }
            set {
                this.rechtsPersoonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VoortzettingEnOverdrachtSignaalType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NieuweInschrijvingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RechtsvormwijzigingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InsolventiewijzigingType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/2016/01")]
    public partial class SignaalType {
        
        private string signaalIdField;
        
        private string registratieIdField;
        
        private string registratieTijdstipField;
        
        /// <remarks/>
        public string signaalId {
            get {
                return this.signaalIdField;
            }
            set {
                this.signaalIdField = value;
            }
        }
        
        /// <remarks/>
        public string registratieId {
            get {
                return this.registratieIdField;
            }
            set {
                this.registratieIdField = value;
            }
        }
        
        /// <remarks/>
        public string registratieTijdstip {
            get {
                return this.registratieTijdstipField;
            }
            set {
                this.registratieTijdstipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/voortzettingenoverdracht/2016/01")]
    [System.Xml.Serialization.XmlRootAttribute("VoortzettingEnOverdracht", Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/voortzettingenoverdracht/2016/01", IsNullable=false)]
    public partial class VoortzettingEnOverdrachtSignaalType : SignaalType {
        
        private string startdatumField;
        
        private MaatschappelijkeActiviteitType heeftBetrekkingOpField;
        
        private VoortzettingEnOverdrachtType voortzettingEnOverdrachtField;
        
        /// <remarks/>
        public string startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
            }
        }
        
        /// <remarks/>
        public MaatschappelijkeActiviteitType heeftBetrekkingOp {
            get {
                return this.heeftBetrekkingOpField;
            }
            set {
                this.heeftBetrekkingOpField = value;
            }
        }
        
        /// <remarks/>
        public VoortzettingEnOverdrachtType voortzettingEnOverdracht {
            get {
                return this.voortzettingEnOverdrachtField;
            }
            set {
                this.voortzettingEnOverdrachtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/nieuweinschrijving/2016/01")]
    [System.Xml.Serialization.XmlRootAttribute("NieuweInschrijving", Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/nieuweinschrijving/2016/01", IsNullable=false)]
    public partial class NieuweInschrijvingType : SignaalType {
        
        private string startdatumField;
        
        private MaatschappelijkeActiviteitType heeftBetrekkingOpField;
        
        private Aanleiding aanleidingField;
        
        /// <remarks/>
        public string startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
            }
        }
        
        /// <remarks/>
        public MaatschappelijkeActiviteitType heeftBetrekkingOp {
            get {
                return this.heeftBetrekkingOpField;
            }
            set {
                this.heeftBetrekkingOpField = value;
            }
        }
        
        /// <remarks/>
        public Aanleiding aanleiding {
            get {
                return this.aanleidingField;
            }
            set {
                this.aanleidingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/rechtsvormwijziging/2016/01")]
    [System.Xml.Serialization.XmlRootAttribute("Rechtsvormwijziging", Namespace="http://schemas.kvk.nl/schemas/hrip/signaal/rechtsvormwijziging/2016/01", IsNullable=false)]
    public partial class RechtsvormwijzigingType : SignaalType {
        
        private string startdatumField;
        
        private MaatschappelijkeActiviteitType heeftBetrekkingOpField;
        
        /// <remarks/>
        public string startdatum {
            get {
                return this.startdatumField;
            }
            set {
                this.startdatumField = value;
            }
        }
        
        /// <remarks/>
        public MaatschappelijkeActiviteitType heeftBetrekkingOp {
            get {
                return this.heeftBetrekkingOpField;
            }
            set {
                this.heeftBetrekkingOpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    [System.Xml.Serialization.XmlRootAttribute("UpdateBericht", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01", IsNullable=false)]
    public partial class UpdateBerichtType : BerichtType {
        
        private MaatschappelijkeActiviteitType1 heeftBetrekkingOpField;
        
        private GegevensblokType[] heeftGewijzigdField;
        
        /// <remarks/>
        public MaatschappelijkeActiviteitType1 heeftBetrekkingOp {
            get {
                return this.heeftBetrekkingOpField;
            }
            set {
                this.heeftBetrekkingOpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heeftGewijzigd")]
        public GegevensblokType[] heeftGewijzigd {
            get {
                return this.heeftGewijzigdField;
            }
            set {
                this.heeftGewijzigdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MaatschappelijkeActiviteitType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class MaatschappelijkeActiviteitType1 {
        
        private string kvkNummerField;
        
        private EnumeratieType1 nonMailingField;
        
        private string totaalWerkzamePersonenField;
        
        private EigenaarType1 heeftAlsEigenaarField;
        
        private VestigingType1[] wordtUitgeoefendInField;
        
        /// <remarks/>
        public string kvkNummer {
            get {
                return this.kvkNummerField;
            }
            set {
                this.kvkNummerField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType1 nonMailing {
            get {
                return this.nonMailingField;
            }
            set {
                this.nonMailingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string totaalWerkzamePersonen {
            get {
                return this.totaalWerkzamePersonenField;
            }
            set {
                this.totaalWerkzamePersonenField = value;
            }
        }
        
        /// <remarks/>
        public EigenaarType1 heeftAlsEigenaar {
            get {
                return this.heeftAlsEigenaarField;
            }
            set {
                this.heeftAlsEigenaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wordtUitgeoefendIn")]
        public VestigingType1[] wordtUitgeoefendIn {
            get {
                return this.wordtUitgeoefendInField;
            }
            set {
                this.wordtUitgeoefendInField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="EnumeratieType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class EnumeratieType1 {
        
        private string codeField;
        
        private string omschrijvingField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="EigenaarType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class EigenaarType1 {
        
        private PersoonType1 itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("natuurlijkPersoon", typeof(NatuurlijkPersoonType1))]
        [System.Xml.Serialization.XmlElementAttribute("rechtsPersoon", typeof(NietNatuurlijkPersoonType1))]
        public PersoonType1 Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NatuurlijkPersoonType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class NatuurlijkPersoonType1 : PersoonType1 {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NatuurlijkPersoonType1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NietNatuurlijkPersoonType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PersoonType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class PersoonType1 {
        
        private string persoonRechtsvormField;
        
        /// <remarks/>
        public string persoonRechtsvorm {
            get {
                return this.persoonRechtsvormField;
            }
            set {
                this.persoonRechtsvormField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NietNatuurlijkPersoonType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class NietNatuurlijkPersoonType1 : PersoonType1 {
        
        private LocatieType1 bezoekAdresField;
        
        private string rsinField;
        
        private ActiviteitType1[] activiteitField;
        
        /// <remarks/>
        public LocatieType1 bezoekAdres {
            get {
                return this.bezoekAdresField;
            }
            set {
                this.bezoekAdresField = value;
            }
        }
        
        /// <remarks/>
        public string rsin {
            get {
                return this.rsinField;
            }
            set {
                this.rsinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activiteit")]
        public ActiviteitType1[] activiteit {
            get {
                return this.activiteitField;
            }
            set {
                this.activiteitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="LocatieType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class LocatieType1 {
        
        private PostcodeType1 postcodeField;
        
        /// <remarks/>
        public PostcodeType1 postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PostcodeType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class PostcodeType1 {
        
        private string cijfercombinatieField;
        
        private string lettercombinatieField;
        
        /// <remarks/>
        public string cijfercombinatie {
            get {
                return this.cijfercombinatieField;
            }
            set {
                this.cijfercombinatieField = value;
            }
        }
        
        /// <remarks/>
        public string lettercombinatie {
            get {
                return this.lettercombinatieField;
            }
            set {
                this.lettercombinatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ActiviteitType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class ActiviteitType1 {
        
        private string sbiCodeField;
        
        private EnumeratieType1 isHoofdactiviteitField;
        
        /// <remarks/>
        public string sbiCode {
            get {
                return this.sbiCodeField;
            }
            set {
                this.sbiCodeField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType1 isHoofdactiviteit {
            get {
                return this.isHoofdactiviteitField;
            }
            set {
                this.isHoofdactiviteitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="VestigingType", Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class VestigingType1 {
        
        private string vestigingsnummerField;
        
        private LocatieType1 bezoekAdresField;
        
        private ActiviteitType1[] activiteitField;
        
        private EnumeratieType1 isHoofdvestigingField;
        
        /// <remarks/>
        public string vestigingsnummer {
            get {
                return this.vestigingsnummerField;
            }
            set {
                this.vestigingsnummerField = value;
            }
        }
        
        /// <remarks/>
        public LocatieType1 bezoekAdres {
            get {
                return this.bezoekAdresField;
            }
            set {
                this.bezoekAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activiteit")]
        public ActiviteitType1[] activiteit {
            get {
                return this.activiteitField;
            }
            set {
                this.activiteitField = value;
            }
        }
        
        /// <remarks/>
        public EnumeratieType1 isHoofdvestiging {
            get {
                return this.isHoofdvestigingField;
            }
            set {
                this.isHoofdvestigingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public partial class GegevensblokType {
        
        private EnumeratieType1 naamField;
        
        /// <remarks/>
        public EnumeratieType1 naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateBerichtType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.kvk.nl/schemas/hrip/update/2016/01")]
    public abstract partial class BerichtType {
        
        private string berichtIdField;
        
        private string registratieIdField;
        
        private string registratieTijdstipField;
        
        /// <remarks/>
        public string berichtId {
            get {
                return this.berichtIdField;
            }
            set {
                this.berichtIdField = value;
            }
        }
        
        /// <remarks/>
        public string registratieId {
            get {
                return this.registratieIdField;
            }
            set {
                this.registratieIdField = value;
            }
        }
        
        /// <remarks/>
        public string registratieTijdstip {
            get {
                return this.registratieTijdstipField;
            }
            set {
                this.registratieTijdstipField = value;
            }
        }
    }
}
